import Head from 'next/head';
import AccountingThroughout from '../components/AccountingThroughout';
import DigitalPersonalAccounting from '../components/DigitalPersonalAccounting';
import OurCustomers from '../components/OurCustomers';
import Quote from '../components/Quote';
import Welcome from '../components/Welcome';
import { homeBannerOptions } from '../lib/bannerOptions';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Welcome bannerOptions={homeBannerOptions} />
      <DigitalPersonalAccounting />
      <Quote size="large" />
      <AccountingThroughout />
      <OurCustomers />
    </>
  );
}
